---
- name: install lamp server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: installing java 17 
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present 
