---
- name: install lamp server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: update packages and install tree
      ansible.builtin.apt:
        name: tree
        state: present
        update_cache: yes
    - name: install apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: installing dot net 7 
      ansible.builtin.apt:
        name: dotnet-sdk-7.0
        update_cache: yes
        state: present 