---
- name: hello ansible
  hosts: all
  become: yes
  tasks:
    - name: update packages and install tree
      ansible.builtin.apt:
        name: tree
        state: present
        update_cache: yes